#ifndef GVENTUSMINILEFTHANDCLOSEDDL_MESH_H
#define GVENTUSMINILEFTHANDCLOSEDDL_MESH_H

#include "ultra64.h"
#include "global.h"

extern u64 gVentusMiniLeftHandClosedDL_mesh_GlovesandBelt_ci4[];
extern u64 gVentusMiniLeftHandClosedDL_mesh_GlovesandBelt_pal_rgba16[];
extern Vtx gVentusMiniLeftHandClosedDL_mesh_gVentusMiniLeftHandClosedDL_mesh_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gVentusMiniLeftHandClosedDL_mesh_gVentusMiniLeftHandClosedDL_mesh_mesh_layer_Opaque_vtx_0[36];
extern Gfx gVentusMiniLeftHandClosedDL_mesh_gVentusMiniLeftHandClosedDL_mesh_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gVentusMiniLeftHandClosedDL_mesh_f3dlite_material_037_layerOpaque[];
extern Gfx mat_revert_gVentusMiniLeftHandClosedDL_mesh_f3dlite_material_037_layerOpaque[];
extern Gfx gVentusMiniLeftHandClosedDL_mesh[];

#endif
