#ifndef GVENTUSKOKIRISHEATHDL_MESH_H
#define GVENTUSKOKIRISHEATHDL_MESH_H

#include "ultra64.h"
#include "global.h"

extern u64 gVentusKokiriSheathDL_mesh_podAS3TC_ci8[];
extern u64 gVentusKokiriSheathDL_mesh_podAS3TC_pal_rgba16[];
extern Vtx gVentusKokiriSheathDL_mesh_gVentusKokiriSheathDL_mesh_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gVentusKokiriSheathDL_mesh_gVentusKokiriSheathDL_mesh_mesh_layer_Opaque_vtx_0[25];
extern Gfx gVentusKokiriSheathDL_mesh_gVentusKokiriSheathDL_mesh_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gVentusKokiriSheathDL_mesh_f3dlite_material_062_layerOpaque[];
extern Gfx mat_revert_gVentusKokiriSheathDL_mesh_f3dlite_material_062_layerOpaque[];
extern Gfx gVentusKokiriSheathDL_mesh[];

#endif
